### ISSUE TITLE
怎么根据后端接口返回的数据渲染

### ISSUE THREAD

**Issue by Xieyxz** [jianjianghui/flow-designer-vue2#1]

**Comment by jianjianghui** [comment]
###  感谢能够提出宝贵的issue，代码写的不好，见谅。

组件示例在 src/components/HelloWorld.vue 中

```js
    let businessAdapter = BusinessAdapter.getBusinessAdapter();
    let nodeData = businessAdapter.getNodeData({workflowId: 'xxx'});
    return {nodeData, businessAdapter};
```

nodeData就是渲染用的数据, nodeHandler.js里面可以获取到整个工作流的配置数据

将 nodeHandler.map().node的结果存到后端以支持根据后端接口返回的数据渲染

**Comment by Xieyxz** [comment]
没有，写得很好，就是我太菜了看不太懂，节点如何绑定数据啊

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月19日 17:03 |
| 收件人 | jianjianghui/flow-designer-vue2 ***@***.***> |
| 抄送人 | Xieyxz ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [jianjianghui/flow-designer-vue2] 怎么根据后端接口返回的数据渲染 (Issue #1) |

感谢能够提出宝贵的issue，代码写的不好，见谅。

组件示例在 src/components/HelloWorld.vue 中

letbusinessAdapter=BusinessAdapter.getBusinessAdapter();letnodeData=businessAdapter.getNodeData({workflowId: 'xxx'});return{nodeData, businessAdapter};

nodeData就是渲染用的数据, nodeHandler.js里面可以获取到整个工作流的配置数据

将 nodeHandler.map()的结果存到后端以支持根据后端接口返回的数据渲染

**Comment by Xieyxz** [comment]
我主要想问的是，不是每个节点都有弹窗设置吗，我是说如何将弹窗设置的数据绑定给节点，然后保存发给后端；编辑的时候如何再将接口返回的数据来渲染图

**Comment by jianjianghui** [comment]
抱歉没能及时回复，工作比较忙

在nodeHandler.map().node 存放了节点的所有数据，包括自定义的业务数据，因此保存发给后端和后端接口返回给前端渲染和之前说的一样。对于如何自定义业务数据，具体操作如下：

在``src/components/flow/designer/node`` 目录下存放所有的节点。进入某个节点例如CheckNode.vue（审批人节点），在template标签结尾可以看到弹窗的内容。在这里去实现自定义的弹窗内容。
```js 
 <a-drawer
        :after-visible-change="change"
        :closable="true"
        :title="node.name"
        :visible="visibleDrawer"
        :width="720"
        placement="right"
        @close="hideDrawer"
    >
      <p>Some contents...</p>
      <p>Some contents...</p>
      <p>Some contents...</p>
    </a-drawer>

```
绑定数据首先需要了解节点是如何定义的，这一部分在``src/components/flow/designer/NodeItem.js``中，它有一个属性 ``data``专用来存储业务数据
```js
import NodeType from "@/components/flow/designer/NodeType";

/**
 * 节点
 */
class NodeItem {
  ....

    /**
     * 业务数据
     * @type {Object}
     */
    data;


    ....
}

export default NodeItem;

```


回到CheckNode，需要修改props中的node来实现节点的业务数据。
但是在vue规范中并不推荐直接修改props中的内容，所以我在实现的过程中使用了取巧的方式，在steup中可以返回 nodeRef: node（当然可以用更好的方式实现它），最后在template中实现数据绑定。

一个简单的例子 (注意进行修改时不要删除已有的内容)：
```js
<template>
 <a-drawer
        :after-visible-change="change"
        :closable="true"
        :title="node.name"
        :visible="visibleDrawer"
        :width="720"
        placement="right"
        @close="hideDrawer"
    >
      <a-input  v-model="nodeRef.name"  placeholder="节点名称" />
      <a-input  v-model="nodeRef.data.xxx"  placeholder="xxxx" />
      <!--   ...  -->
    </a-drawer>
</template>
<script>
export default {
  ....
  setup({node,nodeHandler}) {
    ....
    function defaultData() {
      return {
        xxx: '默认值'
      }
    }
    
    if (!node.data) {
      // eslint-disable-next-line vue/no-mutating-props
      node.data = defaultData()
    }

    return {nodeRef:node,.....}
  }
}
<script>

```

**Comment by Xieyxz** [comment]
不是啊，你说的这些代码有，我是想问那后端返回一组数据，我是问如何通过这组数据画出图来，其次我想问因为每个类型节点的配置信息不一样，比如说我如何在第二节点获取到第一节点的数据

**Comment by jianjianghui** [comment]
Q: 如何通过这组数据画出图来?
A: 实现渲染是通过解析nodeData来实现的，具体解析的逻辑在nodeHandler的构造函数中

Q: 因为每个类型节点的配置信息不一样，比如说我如何在第二节点获取到第一节点的数据？
A: 获取上一个节点的节点的内容可以调用nodeHandler提供的相关函数。nodeHandler.getPreNode可能满足需求。

另外感谢你能关注到这个项目，如果需要完善文档或更好的开发优化思路，敬请提供PR。

**Comment by Xieyxz** [comment]
// 重新创建NodeHandler实例
    recreateNodeHandler() {
      this.nodeHandler = new NodeHandler(this.nodeData);
    },修改了nodeHandler的nodeData，但是图还是原来初始化的那个，这是为什么

**Comment by Xieyxz** [comment]
你说实现渲染是通过解析nodeData来实现的，重新赋值了nodeData，图还是旧的
