### ISSUE TITLE
如何修改nodeHandler的nodeData

### ISSUE THREAD

**Issue by Xieyxz** [jianjianghui/flow-designer-vue2#2]
// 重新创建NodeHandler实例
    recreateNodeHandler() {
      this.nodeHandler = new NodeHandler(this.nodeData);
    },修改了nodeHandler的nodeData，但是图还是原来初始化的那个，这是为什么

**Comment by jianjianghui** [comment]
很抱歉对你造成了困扰，这是基于vue2的项目，却出现了很多跟vue无关的写法。

实际上页面渲染是vue2的基础。nodeData作为nodeContainer组件的props，更新nodeData会触发页面更新
this.nodeHandler = new NodeHandler(this.nodeData); 并不能实现预期效果

**Comment by Xieyxz** [comment]
那怎么样才能更新？

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月21日 18:13 |
| 收件人 | jianjianghui/flow-designer-vue2 ***@***.***> |
| 抄送人 | Xieyxz ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [jianjianghui/flow-designer-vue2] 如何修改nodeHandler的nodeData (Issue #2) |

很抱歉对你造成了困扰，这是基于vue2的项目，却出现了很多跟vue无关的写法。

实际上页面渲染是vue2的基础。nodeData作为nodeContainer组件的props，更新nodeData会触发页面更新
this.nodeHandler = new NodeHandler(this.nodeData); 并不能实现预期效果

**Comment by Xieyxz** [comment]
所以要怎么样才能达到预期效果呢

**Comment by jianjianghui** [comment]
要实现加载整个nodeData

```vue
<template>
  <a @click="load">重新加载</a>
  <NodeContainer v-if="init" :business-adapter="businessAdapter" :node-data="nodeData" />
</template>
<script>

class YourBusiness extends BusinessAdapter { .... }

export default {
  data () {
    let businessAdapter = new YourBusiness(...)
    return {
      init: false,
      nodeData: businessAdapter.getNodeData(),
      businessAdapter: businessAdapter,
    }
  },
  computed: {
    nodeHandler () {
      return this.businessAdapter.nodeHandler
    }
  },
  mounted () {
    this.load()
  }
  method:{
    load() {
      this.init = false
      // YourBusiness的getNodeData方法负责加载nodeData
      this.nodeData = await businessAdapter.getNodeData()
      this.init = true
    },
    commit ()  {
      if (!thisbusinessAdapter.nodeHandler.verify()) {
        this.$message.error('校验未通过')
        return
      }

      const node = this.businessAdapter.nodeHandler.map().node
      this.save(node ? [...Object.values(node)] : [])
    },
    save(data) {
      this.$api.post('xxxx',data)
    }
  }
}
<script>

```

**Comment by Xieyxz** [comment]
啊？大神你是不是理解錯誤了，我想问的是从接口获取数据，通过这个数据重新渲染图

**Comment by jianjianghui** [comment]
await businessAdapter.getNodeData()
getNodeData方法里实现请求接口获取数据

**Comment by Xieyxz** [comment]
class YourBusiness extends BusinessAdapter { .... }，这个，和let businessAdapter = new YourBusiness(...)，继承的什么？还要有自己写方法？

**Comment by Xieyxz** [comment]
class 不常用所以不太理解

**Comment by jianjianghui** [comment]
class YourBusiness extends BusinessAdapter { .... }是一个继承写法
要自己实现YourBusiness里面的getNodeData 方法

**Comment by Xieyxz** [comment]
只能这么写吗？我再其他地方获取的数据，这样的话就更新不了视图？

**Comment by Xieyxz** [comment]
你回答的有点模棱两可，一定要用BusinessAdapter 里面的放个去获取数据吗?我试了也不行啊，我再vue页面调用接口获取了数据，并处理成这个型式[
      {
          name: "审核流",
          code: "审核流",
          type: "start",
          nextNodeCode: "节点一",
        },
        {
          name: "节点一",
          code: "节点一",
          type: "check",
          nextNodeCode: "流程结束",
        },
        {
          name: "流程结束",
          code: "流程结束",
          type: "end",
        },
      ]，然后赋值给nodeData，我现在是想知道怎么去重新渲染图

**Comment by Xieyxz** [comment]
你回答的有点模棱两可，一定要用BusinessAdapter 里面的放个去获取数据吗?我试了也不行啊，我再vue页面调用接口获取了数据，并处理成这个型式[
      {
          name: "审核流",
          code: "审核流",
          type: "start",
          nextNodeCode: "节点一",
        },
        {
          name: "节点一",
          code: "节点一",
          type: "check",
          nextNodeCode: "流程结束",
        },
        {
          name: "流程结束",
          code: "流程结束",
          type: "end",
        },
      ]，然后赋值给nodeData，我现在是想知道怎么去重新渲染图

**Comment by jianjianghui** [comment]
作为初学者出现这种情况是很正常的。好好学习vue，就能看懂渲染的那块代码。其实很简单的，重新渲染的代码已经写在那个示例了。

整个渲染全是基于dom的。没有canvas、WebGL这类复杂的。
